[2025-05-26T18:07:34.618+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-26T18:07:34.630+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:07:34.635+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:07:34.635+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-26T18:07:34.656+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_currency> on 2025-05-26 14:00:00+00:00
[2025-05-26T18:07:34.663+0300] {standard_task_runner.py:63} INFO - Started process 17101 to run task
[2025-05-26T18:07:34.678+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'currency_etl_dag', 'fetch_and_store_currency', 'scheduled__2025-05-26T14:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag.py', '--cfg-path', '/tmp/tmpbhqo0uwu']
[2025-05-26T18:07:34.685+0300] {standard_task_runner.py:91} INFO - Job 18: Subtask fetch_and_store_currency
[2025-05-26T18:07:34.755+0300] {task_command.py:426} INFO - Running <TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [running]> on host Home.
[2025-05-26T18:07:34.827+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='currency_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_currency' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T14:00:00+00:00'
[2025-05-26T18:07:34.831+0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-26T18:07:35.641+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-26T18:07:35.642+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/airflow/dags/fetch_currency_data.py", line 9, in fetch_and_store_currency
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-26T18:07:35.660+0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_etl_dag, task_id=fetch_and_store_currency, run_id=scheduled__2025-05-26T14:00:00+00:00, execution_date=20250526T140000, start_date=20250526T150734, end_date=20250526T150735
[2025-05-26T18:07:35.677+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task fetch_and_store_currency (connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 17101)
[2025-05-26T18:07:35.696+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-26T18:07:35.706+0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T18:07:35.707+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-26T18:20:19.408+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-26T18:20:19.428+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:20:19.432+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:20:19.432+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-26T18:20:19.454+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_currency> on 2025-05-26 14:00:00+00:00
[2025-05-26T18:20:19.458+0300] {standard_task_runner.py:63} INFO - Started process 18399 to run task
[2025-05-26T18:20:19.463+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'currency_etl_dag', 'fetch_and_store_currency', 'scheduled__2025-05-26T14:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag.py', '--cfg-path', '/tmp/tmpbhykahfz']
[2025-05-26T18:20:19.465+0300] {standard_task_runner.py:91} INFO - Job 2: Subtask fetch_and_store_currency
[2025-05-26T18:20:19.519+0300] {task_command.py:426} INFO - Running <TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [running]> on host Home.
[2025-05-26T18:20:19.607+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='currency_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_currency' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T14:00:00+00:00'
[2025-05-26T18:20:19.610+0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-26T18:20:20.384+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-26T18:20:20.384+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/airflow/dags/fetch_currency_data.py", line 18, in fetch_and_store_currency
    cur.execute("""
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:         CREATE TABLE IF NOT EXISTS currency_rates (
                                           ^

[2025-05-26T18:20:20.391+0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_etl_dag, task_id=fetch_and_store_currency, run_id=scheduled__2025-05-26T14:00:00+00:00, execution_date=20250526T140000, start_date=20250526T152019, end_date=20250526T152020
[2025-05-26T18:20:20.407+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task fetch_and_store_currency (permission denied for schema public
LINE 2:         CREATE TABLE IF NOT EXISTS currency_rates (
                                           ^
; 18399)
[2025-05-26T18:20:20.441+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-26T18:20:20.450+0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T18:20:20.450+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
