[2025-05-26T18:12:38.362+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-26T18:12:38.373+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:12:38.379+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:12:38.379+0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-26T18:12:38.395+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_currency> on 2025-05-26 14:00:00+00:00
[2025-05-26T18:12:38.398+0300] {standard_task_runner.py:63} INFO - Started process 17497 to run task
[2025-05-26T18:12:38.403+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'currency_etl_dag', 'fetch_and_store_currency', 'scheduled__2025-05-26T14:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag.py', '--cfg-path', '/tmp/tmp_g__0aqi']
[2025-05-26T18:12:38.405+0300] {standard_task_runner.py:91} INFO - Job 21: Subtask fetch_and_store_currency
[2025-05-26T18:12:38.450+0300] {task_command.py:426} INFO - Running <TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [running]> on host Home.
[2025-05-26T18:12:38.513+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='currency_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_currency' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T14:00:00+00:00'
[2025-05-26T18:12:38.515+0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-26T18:12:39.324+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-26T18:12:39.325+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/airflow/dags/fetch_currency_data.py", line 9, in fetch_and_store_currency
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-26T18:12:39.334+0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=currency_etl_dag, task_id=fetch_and_store_currency, run_id=scheduled__2025-05-26T14:00:00+00:00, execution_date=20250526T140000, start_date=20250526T151238, end_date=20250526T151239
[2025-05-26T18:12:39.351+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task fetch_and_store_currency (connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 17497)
[2025-05-26T18:12:39.380+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-26T18:12:39.389+0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T18:12:39.390+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-26T18:25:23.051+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-26T18:25:23.064+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:25:23.070+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [queued]>
[2025-05-26T18:25:23.070+0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-26T18:25:23.087+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_currency> on 2025-05-26 14:00:00+00:00
[2025-05-26T18:25:23.090+0300] {standard_task_runner.py:63} INFO - Started process 18896 to run task
[2025-05-26T18:25:23.092+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'currency_etl_dag', 'fetch_and_store_currency', 'scheduled__2025-05-26T14:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag.py', '--cfg-path', '/tmp/tmp5701wc1w']
[2025-05-26T18:25:23.093+0300] {standard_task_runner.py:91} INFO - Job 5: Subtask fetch_and_store_currency
[2025-05-26T18:25:23.137+0300] {task_command.py:426} INFO - Running <TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T14:00:00+00:00 [running]> on host Home.
[2025-05-26T18:25:23.191+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='currency_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_currency' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T14:00:00+00:00'
[2025-05-26T18:25:23.194+0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-26T18:25:23.951+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-26T18:25:23.951+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/airflow/dags/fetch_currency_data.py", line 18, in fetch_and_store_currency
    cur.execute("""
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:         CREATE TABLE IF NOT EXISTS currency_rates (
                                           ^

[2025-05-26T18:25:23.956+0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=currency_etl_dag, task_id=fetch_and_store_currency, run_id=scheduled__2025-05-26T14:00:00+00:00, execution_date=20250526T140000, start_date=20250526T152523, end_date=20250526T152523
[2025-05-26T18:25:23.973+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task fetch_and_store_currency (permission denied for schema public
LINE 2:         CREATE TABLE IF NOT EXISTS currency_rates (
                                           ^
; 18896)
[2025-05-26T18:25:23.991+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-26T18:25:24.003+0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T18:25:24.004+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
