[2025-05-26T18:07:38.041+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-26T18:07:38.055+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency manual__2025-05-26T14:53:15+00:00 [queued]>
[2025-05-26T18:07:38.059+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency manual__2025-05-26T14:53:15+00:00 [queued]>
[2025-05-26T18:07:38.060+0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-26T18:07:38.076+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_currency> on 2025-05-26 14:53:15+00:00
[2025-05-26T18:07:38.084+0300] {standard_task_runner.py:63} INFO - Started process 17113 to run task
[2025-05-26T18:07:38.109+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'currency_etl_dag', 'fetch_and_store_currency', 'manual__2025-05-26T14:53:15+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag.py', '--cfg-path', '/tmp/tmpm1kpena1']
[2025-05-26T18:07:38.118+0300] {standard_task_runner.py:91} INFO - Job 19: Subtask fetch_and_store_currency
[2025-05-26T18:07:38.240+0300] {task_command.py:426} INFO - Running <TaskInstance: currency_etl_dag.fetch_and_store_currency manual__2025-05-26T14:53:15+00:00 [running]> on host Home.
[2025-05-26T18:07:38.349+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='currency_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_currency' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T14:53:15+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-26T14:53:15+00:00'
[2025-05-26T18:07:38.353+0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-26T18:07:39.064+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-26T18:07:39.064+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/airflow/dags/fetch_currency_data.py", line 9, in fetch_and_store_currency
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-26T18:07:39.070+0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=currency_etl_dag, task_id=fetch_and_store_currency, run_id=manual__2025-05-26T14:53:15+00:00, execution_date=20250526T145315, start_date=20250526T150738, end_date=20250526T150739
[2025-05-26T18:07:39.090+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task fetch_and_store_currency (connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 17113)
[2025-05-26T18:07:39.104+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-26T18:07:39.117+0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T18:07:39.118+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
